// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'uflacs',
//   'scalar_type': 'double',
//   'timeout': 10}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_ffc_element_23a91cf7fa716ce96f30c788c2ba692ffb77505d_finite_element_main(void);

ufc_finite_element* create_ffc_element_5084e7b6af68dbe00b9b085f4a08f1f7e9c9fb74_finite_element_main(void);

ufc_dofmap* create_ffc_element_23a91cf7fa716ce96f30c788c2ba692ffb77505d_dofmap_main(void);

ufc_dofmap* create_ffc_element_5084e7b6af68dbe00b9b085f4a08f1f7e9c9fb74_dofmap_main(void);

ufc_coordinate_mapping* create_ffc_coordinate_mapping_fea82c10d090ec9472705b246361d217f40bfb17_coordinate_mapping_main(void);

ufc_integral* create_poisson_cell_integral_0_otherwise(void);

ufc_integral* create_poisson_cell_integral_1_otherwise(void);

ufc_integral* create_poisson_exterior_facet_integral_1_otherwise(void);

ufc_form* create_poisson_form_0(void);

ufc_form* create_poisson_form_1(void);


// Typedefs for convenience pointers to functions (factories)
typedef ufc_function_space* (*ufc_function_space_factory_ptr)(void);
typedef ufc_form* (*ufc_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 2)
ufc_function_space* poisson_coefficientspace_f_create(void);
ufc_function_space* poisson_coefficientspace_g_create(void);

// Form function spaces helpers (form 'a')
ufc_function_space* poisson_form_a_functionspace_0_create(void);

ufc_function_space* poisson_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
/*   - No form coefficients */
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_a_create = create_poisson_form_0;

/*    Typedefs (function spaces for form_a) */
static const ufc_function_space_factory_ptr poisson_form_a_testspace_create = poisson_form_a_functionspace_0_create;
static const ufc_function_space_factory_ptr poisson_form_a_trialspace_create = poisson_form_a_functionspace_1_create;


 /* End coefficient typedefs */

// Form function spaces helpers (form 'L')
ufc_function_space* poisson_form_L_functionspace_0_create(void);

/* Coefficient function space typedefs for form "form_L" */
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_1_create = poisson_coefficientspace_f_create;
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_2_create = poisson_coefficientspace_g_create;
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_L_create = create_poisson_form_1;

/*    Typedefs (function spaces for form_L) */
static const ufc_function_space_factory_ptr poisson_form_L_testspace_create = poisson_form_L_functionspace_0_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_f_create = poisson_form_L__functionspace_1_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_g_create = poisson_form_L__functionspace_2_create;

 /* End coefficient typedefs */

/* Start high-level typedefs */
static const ufc_form_factory_ptr poisson_bilinearform_create = poisson_form_a_create;
static const ufc_form_factory_ptr poisson_linearform_create = poisson_form_L_create;

static const ufc_function_space_factory_ptr poisson_functionspace_create = poisson_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
