#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'form_postfix': False,
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'auto',
//   'scalar_type': 'double',
//   'timeout': 10}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main

int value_dimension_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(int i)
{
  return 1;
}

int reference_value_dimension_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(int i)
{
  return 1;
}

int evaluate_reference_basis_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(double* restrict reference_values,
                                            int num_points,
                                            const double* restrict X)
{
  static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
for (int64_t k = 0; k < num_points * 3; ++k)
    reference_values[k] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Accumulate products of coefficients and basisvalues
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip + 1] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip + 2] += coefficients2[0][r] * basisvalues1[r];
}
return 0;
}

int evaluate_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(double * restrict reference_values,
                                          int order, int num_points,
                                          const double * restrict X)
{
  if (order == 0)
    return evaluate_reference_basis_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(reference_values, num_points, X);
const int64_t num_derivatives = pow(2, order);
for (int64_t l0 = 0; l0 < num_points * 3 * num_derivatives; ++l0)
    reference_values[l0] = 0.0;
if (order > 1)
    return 0;
// Tables of derivatives of the polynomial base (transpose).
alignas(32) static const double dmats0[2][3][3] =
    { { { 0.0, 0.0, 0.0 },
        { 4.8989794855663495, 0.0, 0.0 },
        { 0.0, 0.0, 0.0 } },
      { { 0.0, 0.0, 0.0 },
        { 2.449489742783182, 0.0, 0.0 },
        { 4.242640687119285, 0.0, 0.0 } } };
static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
const int64_t reference_offset[3] = { 0 };
const int64_t num_components[3] = { 1, 1, 1 };
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Loop over all dofs
    for (int64_t i = 0; i < 3; ++i)
    {
        double derivatives[2] = { 0 };
        switch (i)
        {
        case 0:
            // Compute reference derivatives for dof 0.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 1:
            // Compute reference derivatives for dof 1.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 2:
            // Compute reference derivatives for dof 2.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        }
        for (int64_t r = 0; r < num_derivatives; ++r)
            for (int64_t c = 0; c < num_components[i]; ++c)
                reference_values[3 * num_derivatives * ip + num_derivatives * i + r + (reference_offset[i] + c)] = derivatives[num_derivatives * c + r];
    }
}
return 0;
}

int transform_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K,
    int cell_orientation)
{
  const int64_t num_derivatives_t = pow(2, order);
const int64_t num_derivatives_g = pow(3, order);
// Precomputed combinations
const int64_t combinations_t[1][2][1] =
    { { { 0 },
        { 1 } } };
// Precomputed combinations
const int64_t combinations_g[1][3][1] =
    { { { 0 },
        { 1 },
        { 2 } } };
for (int64_t l = 0; l < num_points * 3 * num_derivatives_g; ++l)
    values[l] = 0.0;
const int64_t reference_offsets[3] = { 0 };
const int64_t physical_offsets[3] = { 0 };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    double transform[3][2];
    for (int64_t r = 0; r < num_derivatives_g; ++r)
        for (int64_t s = 0; s < num_derivatives_t; ++s)
            transform[r][s] = 1.0;
    for (int64_t r = 0; r < num_derivatives_g; ++r)
        for (int64_t s = 0; s < num_derivatives_t; ++s)
            for (int64_t k = 0; k < order; ++k)
                transform[r][s] *= K[2 * 3 * ip + 3 * combinations_t[order - 1][s][k] + combinations_g[order - 1][r][k]];
    for (int64_t d = 0; d < 3; ++d)
    {
        for (int64_t s = 0; s < num_derivatives_t; ++s)
        {
            for (int64_t i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[3 * num_derivatives_t * ip + num_derivatives_t * d + s + reference_offsets[d]];
                // Mapping derivatives back to the physical element
                for (int64_t r = 0; r < num_derivatives_g; ++r)
                    values[3 * num_derivatives_g * ip + num_derivatives_g * d + r + (physical_offsets[d] + i)] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}

int transform_values_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(
     ufc_scalar_t* restrict reference_values,
     const ufc_scalar_t* restrict physical_values,
     const double* restrict coordinate_dofs,
     int cell_orientation,
     const ufc_coordinate_mapping* cm)
{
  reference_values[0] = physical_values[0];
reference_values[1] = physical_values[1];
reference_values[2] = physical_values[2];
return 0;
}

int tabulate_reference_dof_coordinates_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(double* restrict reference_dof_coordinates)
{
  static const double dof_X[6] = { 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 };
memcpy(reference_dof_coordinates, dof_X, 6*sizeof(double));
return 0;
}


ufc_finite_element* create_sub_element_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(int i)
{
  return NULL;
}

ufc_finite_element* create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(void)
{
  ufc_finite_element* element = malloc(sizeof(*element));

  element->signature = "FiniteElement('Lagrange', Cell('triangle', 3), 1)";
  element->cell_shape = triangle;
  element->topological_dimension = 2;
  element->geometric_dimension = 3;
  element->space_dimension = 3;
  element->value_rank = 0;
  element->value_dimension = value_dimension_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->value_size = 1;
  element->reference_value_rank = 0;
  element->reference_value_dimension = reference_value_dimension_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->reference_value_size = 1;
  element->degree = 1;
  element->family = "Lagrange";
  element->evaluate_reference_basis = evaluate_reference_basis_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->evaluate_reference_basis_derivatives = evaluate_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->transform_values = transform_values_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->tabulate_reference_dof_coordinates = tabulate_reference_dof_coordinates_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->num_sub_elements = 0;
  element->create_sub_element = create_sub_element_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;
  element->create = create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main;

  return element;
};

// End of code for element ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main

// Code for element ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main

int value_dimension_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(int i)
{
  static const int return_values[1] = { 3 };
if (i >= 1)
    return 1;
return return_values[i];
}

int reference_value_dimension_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(int i)
{
  static const int return_values[1] = { 3 };
if (i >= 1)
    return 1;
return return_values[i];
}

int evaluate_reference_basis_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(double* restrict reference_values,
                                            int num_points,
                                            const double* restrict X)
{
  static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
for (int64_t k = 0; k < num_points * 9 * 3; ++k)
    reference_values[k] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Accumulate products of coefficients and basisvalues
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 2] += coefficients2[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 3 + 1] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 4 + 1] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 5 + 1] += coefficients2[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 6 + 2] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 7 + 2] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[9 * 3 * ip + 3 * 8 + 2] += coefficients2[0][r] * basisvalues1[r];
}
return 0;
}

int evaluate_reference_basis_derivatives_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(double * restrict reference_values,
                                          int order, int num_points,
                                          const double * restrict X)
{
  if (order == 0)
    return evaluate_reference_basis_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(reference_values, num_points, X);
const int64_t num_derivatives = pow(2, order);
for (int64_t l0 = 0; l0 < num_points * 9 * num_derivatives * 3; ++l0)
    reference_values[l0] = 0.0;
if (order > 1)
    return 0;
// Tables of derivatives of the polynomial base (transpose).
alignas(32) static const double dmats0[2][3][3] =
    { { { 0.0, 0.0, 0.0 },
        { 4.8989794855663495, 0.0, 0.0 },
        { 0.0, 0.0, 0.0 } },
      { { 0.0, 0.0, 0.0 },
        { 2.449489742783182, 0.0, 0.0 },
        { 4.242640687119285, 0.0, 0.0 } } };
static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
const int64_t reference_offset[9] = { 0, 0, 0, 1, 1, 1, 2, 2, 2 };
const int64_t num_components[9] = { 1, 1, 1, 1, 1, 1, 1, 1, 1 };
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Loop over all dofs
    for (int64_t i = 0; i < 9; ++i)
    {
        double derivatives[2] = { 0 };
        switch (i)
        {
        case 0:
            // Compute reference derivatives for dof 0.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 1:
            // Compute reference derivatives for dof 1.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 2:
            // Compute reference derivatives for dof 2.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        case 3:
            // Compute reference derivatives for dof 3.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 4:
            // Compute reference derivatives for dof 4.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 5:
            // Compute reference derivatives for dof 5.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        case 6:
            // Compute reference derivatives for dof 6.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 7:
            // Compute reference derivatives for dof 7.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 8:
            // Compute reference derivatives for dof 8.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        }
        for (int64_t r = 0; r < num_derivatives; ++r)
            for (int64_t c = 0; c < num_components[i]; ++c)
                reference_values[9 * (num_derivatives * 3) * ip + num_derivatives * 3 * i + 3 * r + (reference_offset[i] + c)] = derivatives[num_derivatives * c + r];
    }
}
return 0;
}

int transform_reference_basis_derivatives_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K,
    int cell_orientation)
{
  const int64_t num_derivatives_t = pow(2, order);
const int64_t num_derivatives_g = pow(3, order);
// Precomputed combinations
const int64_t combinations_t[1][2][1] =
    { { { 0 },
        { 1 } } };
// Precomputed combinations
const int64_t combinations_g[1][3][1] =
    { { { 0 },
        { 1 },
        { 2 } } };
for (int64_t l = 0; l < num_points * 9 * num_derivatives_g * 3; ++l)
    values[l] = 0.0;
const int64_t reference_offsets[9] = { 0, 0, 0, 1, 1, 1, 2, 2, 2 };
const int64_t physical_offsets[9] = { 0, 0, 0, 1, 1, 1, 2, 2, 2 };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    double transform[3][2];
    for (int64_t r = 0; r < num_derivatives_g; ++r)
        for (int64_t s = 0; s < num_derivatives_t; ++s)
            transform[r][s] = 1.0;
    for (int64_t r = 0; r < num_derivatives_g; ++r)
        for (int64_t s = 0; s < num_derivatives_t; ++s)
            for (int64_t k = 0; k < order; ++k)
                transform[r][s] *= K[2 * 3 * ip + 3 * combinations_t[order - 1][s][k] + combinations_g[order - 1][r][k]];
    for (int64_t d = 0; d < 9; ++d)
    {
        for (int64_t s = 0; s < num_derivatives_t; ++s)
        {
            for (int64_t i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[9 * (num_derivatives_t * 3) * ip + num_derivatives_t * 3 * d + 3 * s + reference_offsets[d]];
                // Mapping derivatives back to the physical element
                for (int64_t r = 0; r < num_derivatives_g; ++r)
                    values[9 * (num_derivatives_g * 3) * ip + num_derivatives_g * 3 * d + 3 * r + (physical_offsets[d] + i)] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}

int transform_values_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(
     ufc_scalar_t* restrict reference_values,
     const ufc_scalar_t* restrict physical_values,
     const double* restrict coordinate_dofs,
     int cell_orientation,
     const ufc_coordinate_mapping* cm)
{
  reference_values[0] = physical_values[0];
reference_values[1] = physical_values[3];
reference_values[2] = physical_values[6];
reference_values[3] = physical_values[10];
reference_values[4] = physical_values[13];
reference_values[5] = physical_values[16];
reference_values[6] = physical_values[20];
reference_values[7] = physical_values[23];
reference_values[8] = physical_values[26];
return 0;
}

int tabulate_reference_dof_coordinates_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(double* restrict reference_dof_coordinates)
{
  static const double dof_X[18] = { 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 };
memcpy(reference_dof_coordinates, dof_X, 18*sizeof(double));
return 0;
}

ufc_finite_element* create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(void);

ufc_finite_element* create_sub_element_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(int i)
{
  switch (i)
{
case 0:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main();
case 1:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main();
case 2:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main();
default:
    return NULL;
}
}

ufc_finite_element* create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(void)
{
  ufc_finite_element* element = malloc(sizeof(*element));

  element->signature = "VectorElement(FiniteElement('Lagrange', Cell('triangle', 3), 1), dim=3)";
  element->cell_shape = triangle;
  element->topological_dimension = 2;
  element->geometric_dimension = 3;
  element->space_dimension = 9;
  element->value_rank = 1;
  element->value_dimension = value_dimension_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->value_size = 3;
  element->reference_value_rank = 1;
  element->reference_value_dimension = reference_value_dimension_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->reference_value_size = 3;
  element->degree = 1;
  element->family = "Lagrange";
  element->evaluate_reference_basis = evaluate_reference_basis_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->evaluate_reference_basis_derivatives = evaluate_reference_basis_derivatives_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->transform_values = transform_values_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->tabulate_reference_dof_coordinates = tabulate_reference_dof_coordinates_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->num_sub_elements = 3;
  element->create_sub_element = create_sub_element_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;
  element->create = create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main;

  return element;
};

// End of code for element ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main

// Code for dofmap ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main

void tabulate_entity_dofs_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}


ufc_dofmap* create_sub_dofmap_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main(int i)
{
return NULL;
}

ufc_dofmap* create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main(void)
{
  ufc_dofmap* dofmap = malloc(sizeof(*dofmap));
  dofmap->signature = "FFC dofmap for FiniteElement('Lagrange', Cell('triangle', 3), 1)";
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 3;
  dofmap->num_entity_dofs[0] = 1;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main;
  dofmap->num_sub_dofmaps = 0;
  dofmap->create_sub_dofmap = create_sub_dofmap_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main;
  dofmap->create = create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main;

  return dofmap;
};

// End of code for dofmap ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main

// Code for dofmap ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main

void tabulate_entity_dofs_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 3;
        dofs[2] = 6;
        break;
    case 1:
        dofs[0] = 1;
        dofs[1] = 4;
        dofs[2] = 7;
        break;
    case 2:
        dofs[0] = 2;
        dofs[1] = 5;
        dofs[2] = 8;
        break;
    }
    break;
}
}

ufc_dofmap* create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main(void);

ufc_dofmap* create_sub_dofmap_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main();
case 1:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main();
case 2:
    return create_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_dofmap_main();
default:
    return NULL;
}
}

ufc_dofmap* create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main(void)
{
  ufc_dofmap* dofmap = malloc(sizeof(*dofmap));
  dofmap->signature = "FFC dofmap for VectorElement(FiniteElement('Lagrange', Cell('triangle', 3), 1), dim=3)";
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 9;
  dofmap->num_entity_dofs[0] = 3;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main;
  dofmap->num_sub_dofmaps = 3;
  dofmap->create_sub_dofmap = create_sub_dofmap_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main;
  dofmap->create = create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main;

  return dofmap;
};

// End of code for dofmap ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main

// Code for coordinate mapping ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main

ufc_finite_element* create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main(void);

ufc_finite_element* create_coordinate_finite_element_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(void)
{
return create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_finite_element_main();
}

ufc_dofmap* create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main(void);

ufc_dofmap* create_coordinate_dofmap_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(void)
{
return create_ffc_element_57c9b91e81d4799172972b733c247cccb2c1aeae_dofmap_main();
}


int evaluate_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(double* restrict reference_values,
    int order, int num_points, const double* restrict X);

void compute_jacobians_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict J, int num_points,
                                      const double* restrict X,
                                      const double* restrict coordinate_dofs)
{
double dphi[6];
for (int64_t l = 0; l < num_points * 3 * 2; ++l)
    J[l] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Compute basis derivatives of coordinate element
    evaluate_reference_basis_derivatives_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(dphi, 1, 1, &X[2 * ip]);
    // Compute J
    for (int64_t i = 0; i < 3; ++i)
        for (int64_t j = 0; j < 2; ++j)
            for (int64_t d = 0; d < 3; ++d)
                J[3 * 2 * ip + 2 * i + j] += coordinate_dofs[3 * d + i] * dphi[2 * d + j];
}
}

void compute_jacobian_determinants_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict detJ, int num_points,
                                                  const double* restrict J, int cell_orientation)
{
for (int64_t ip = 0; ip < num_points; ++ip)
{
    double JTJ[2][2] = {{ 0 }};
    for (int64_t i = 0; i < 2; ++i)
        for (int64_t j = 0; j < 2; ++j)
            for (int64_t k = 0; k < 3; ++k)
                JTJ[i][j] += J[3 * 2 * ip + 2 * k + i] * J[3 * 2 * ip + 2 * k + j];
    detJ[ip] = (cell_orientation == 1 ? -1.0 : 1.0) * sqrt(JTJ[0][0] * JTJ[1][1] - JTJ[0][1] * JTJ[1][0]);
}
}

void compute_jacobian_inverses_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict K, int num_points,
    const double* restrict J, const double* restrict detJ)
{
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Compute J^T J
    double JTJ[4] = { 0 };
    for (int64_t k = 0; k < 2; ++k)
        for (int64_t j = 0; j < 2; ++j)
            for (int64_t i = 0; i < 3; ++i)
                JTJ[2 * k + j] += J[3 * 2 * ip + 2 * i + k] * J[3 * 2 * ip + 2 * i + j];
    // Compute inverse(J^T J)
    double JTJinv[4];
    JTJinv[0] = JTJ[2 + 1] / (detJ[ip] * detJ[ip]);
    JTJinv[1] = -JTJ[1] / (detJ[ip] * detJ[ip]);
    JTJinv[2] = -JTJ[2] / (detJ[ip] * detJ[ip]);
    JTJinv[2 + 1] = JTJ[0] / (detJ[ip] * detJ[ip]);
    // Compute K = inverse(J^T J) * J
    for (int64_t k = 0; k < 2; ++k)
        for (int64_t i = 0; i < 3; ++i)
            K[2 * 3 * ip + 3 * k + i] = 0.0;
    for (int64_t k = 0; k < 2; ++k)
        for (int64_t i = 0; i < 3; ++i)
            for (int64_t j = 0; j < 2; ++j)
                K[2 * 3 * ip + 3 * k + i] += JTJinv[2 * k + j] * J[3 * 2 * ip + 2 * i + j];
}
}


int evaluate_reference_basis_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(double* restrict reference_values,
    int num_points, const double* restrict X);

void compute_physical_coordinates_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict x, int num_points,
                                                 const double* restrict X,
                                                 const double* restrict coordinate_dofs)
{
double phi[3];
for (int64_t i = 0; i < num_points * 3; ++i)
    x[i] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Compute basis values of coordinate element
    evaluate_reference_basis_ffc_element_8966abf9c6f3692405756ca2b77f20debe5f6b0c_finite_element_main(phi, 1, &X[2 * ip]);
    // Compute x
    for (int64_t i = 0; i < 3; ++i)
        for (int64_t d = 0; d < 3; ++d)
            x[3 * ip + i] += coordinate_dofs[3 * d + i] * phi[d];
}
}

void compute_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict x, double* restrict J,
                                     double* restrict detJ, double* restrict K,
                                     int num_points, const double* restrict X,
                                     const double* restrict coordinate_dofs,
                                     int cell_orientation)
{
compute_physical_coordinates_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(x, num_points, X, coordinate_dofs);
compute_jacobians_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(J, num_points, X, coordinate_dofs);
compute_jacobian_determinants_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(detJ, num_points, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(K, num_points, J, detJ);
}

void compute_midpoint_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict x, double* restrict J,
                                              const double* restrict coordinate_dofs)
{
const double phi_Xm[3] = { 0.33333333333333337, 0.33333333333333337, 0.3333333333333333 };
const double dphi_Xm[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
for (int64_t l = 0; l < 6; ++l)
    J[l] = 0.0;
// Compute x
for (int64_t i = 0; i < 3; ++i)
{
    x[i] = 0.0;
    for (int64_t d = 0; d < 3; ++d)
        x[i] += coordinate_dofs[3 * d + i] * phi_Xm[d];
}
// Compute J
for (int64_t i = 0; i < 3; ++i)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t d = 0; d < 3; ++d)
            J[2 * i + j] += coordinate_dofs[3 * d + i] * dphi_Xm[j][d];
}

void compute_reference_coordinates_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict X, int num_points,
                                                  const double* restrict x,
                                                  const double* restrict coordinate_dofs,
                                                  int cell_orientation)
{
for (int64_t l = 0; l < num_points * 2; ++l)
    X[l] = 0.0;
const double phi_X0[3] = { 1.0, 0.0, 0.0 };
const double dphi_X0[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
double J[6];
double detJ[1];
double K[6];
double x0[3] = { 0 };
for (int64_t i = 0; i < 3; ++i)
    for (int64_t k = 0; k < 3; ++k)
        x0[i] += coordinate_dofs[3 * k + i] * phi_X0[k];
for (int64_t i = 0; i < 3; ++i)
{
    for (int64_t j = 0; j < 2; ++j)
    {
        J[2 * i + j] = 0.0;
        for (int64_t k = 0; k < 3; ++k)
            J[2 * i + j] += coordinate_dofs[3 * k + i] * dphi_X0[j][k];
    }
}
compute_jacobian_determinants_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(detJ, 1, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(K, 1, J, detJ);
for (int64_t ip = 0; ip < num_points; ++ip)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t i = 0; i < 3; ++i)
            X[2 * ip + j] += K[3 * j + i] * (x[3 * ip + i] - x0[i]);
}

void compute_reference_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(double* restrict X, double* restrict J,
                                               double* restrict detJ, double* restrict K,
                                               int num_points, const double* restrict x,
                                               const double* restrict coordinate_dofs,
                                               int cell_orientation)
{
for (int64_t l = 0; l < num_points * 2; ++l)
    X[l] = 0.0;
const double phi_X0[3] = { 1.0, 0.0, 0.0 };
const double dphi_X0[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
double x0[3] = { 0 };
for (int64_t i = 0; i < 3; ++i)
    for (int64_t k = 0; k < 3; ++k)
        x0[i] += coordinate_dofs[3 * k + i] * phi_X0[k];
for (int64_t i = 0; i < 3; ++i)
{
    for (int64_t j = 0; j < 2; ++j)
    {
        J[2 * i + j] = 0.0;
        for (int64_t k = 0; k < 3; ++k)
            J[2 * i + j] += coordinate_dofs[3 * k + i] * dphi_X0[j][k];
    }
}
compute_jacobian_determinants_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(detJ, 1, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(K, 1, J, detJ);
for (int64_t ip = 0; ip < num_points; ++ip)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t i = 0; i < 3; ++i)
            X[2 * ip + j] += K[3 * j + i] * (x[3 * ip + i] - x0[i]);
}




ufc_coordinate_mapping* create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(void)
{
  ufc_coordinate_mapping* cmap = malloc(sizeof(*cmap));
  cmap->signature = "FFC coordinate_mapping from VectorElement(FiniteElement('Lagrange', Cell('triangle', 3), 1), dim=3)";
  cmap->create = create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->geometric_dimension = 3;
  cmap->topological_dimension = 2;
  cmap->cell_shape = triangle;
  cmap->create_coordinate_finite_element = create_coordinate_finite_element_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->create_coordinate_dofmap = create_coordinate_dofmap_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_physical_coordinates = compute_physical_coordinates_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_reference_coordinates = compute_reference_coordinates_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_reference_geometry = compute_reference_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_jacobians = compute_jacobians_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_jacobian_determinants = compute_jacobian_determinants_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_jacobian_inverses = compute_jacobian_inverses_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_geometry = compute_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  cmap->compute_midpoint_geometry = compute_midpoint_geometry_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main;
  return cmap;
}

// End of code for coordinate mapping ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 44), // ufc_coordinate_mapping *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 47), // ufc_dofmap *()(void)
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION, 50), // ufc_finite_element *()(void)
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(double *, double *, double *, double *, int, double const *, double const *, int)
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // double *
/*  8 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // double const *
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(double *, double *, double const *)
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(double *, int, double const *, double const *)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(double *, int, double const *, double const *, int)
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(double *, int, double const *, int)
/* 35 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 37 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const *
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 43 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // ufc_coordinate_mapping *(*)(void)
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // ufc_coordinate_mapping *
/* 45 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufc_coordinate_mapping
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // ufc_dofmap *(*)(void)
/* 47 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // ufc_dofmap *
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufc_dofmap
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 4), // ufc_finite_element *(*)(void)
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufc_finite_element *
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufc_finite_element
/* 52 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufc_shape
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // void(*)(double *, double *, double *, double *, int, double const *, double const *, int)
/* 54 */ _CFFI_OP(_CFFI_OP_POINTER, 16), // void(*)(double *, double *, double const *)
/* 55 */ _CFFI_OP(_CFFI_OP_POINTER, 21), // void(*)(double *, int, double const *, double const *)
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(double *, int, double const *, double const *, int)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 34), // void(*)(double *, int, double const *, int)
/* 58 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static ufc_coordinate_mapping * _cffi_d_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(void)
{
  return create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(PyObject *self, PyObject *noarg)
{
  ufc_coordinate_mapping * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(44));
}
#else
#  define _cffi_f_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main _cffi_d_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_coordinate_mapping(ufc_coordinate_mapping *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufc_coordinate_mapping *(* *tmp)(void) = &p->create; (void)tmp; }
  (void)((p->geometric_dimension) | 0);  /* check that 'ufc_coordinate_mapping.geometric_dimension' is an integer */
  (void)((p->topological_dimension) | 0);  /* check that 'ufc_coordinate_mapping.topological_dimension' is an integer */
  { ufc_shape *tmp = &p->cell_shape; (void)tmp; }
  { ufc_finite_element *(* *tmp)(void) = &p->create_coordinate_finite_element; (void)tmp; }
  { ufc_dofmap *(* *tmp)(void) = &p->create_coordinate_dofmap; (void)tmp; }
  { void(* *tmp)(double *, int, double const *, double const *) = &p->compute_physical_coordinates; (void)tmp; }
  { void(* *tmp)(double *, int, double const *, double const *, int) = &p->compute_reference_coordinates; (void)tmp; }
  { void(* *tmp)(double *, double *, double *, double *, int, double const *, double const *, int) = &p->compute_reference_geometry; (void)tmp; }
  { void(* *tmp)(double *, int, double const *, double const *) = &p->compute_jacobians; (void)tmp; }
  { void(* *tmp)(double *, int, double const *, int) = &p->compute_jacobian_determinants; (void)tmp; }
  { void(* *tmp)(double *, int, double const *, double const *) = &p->compute_jacobian_inverses; (void)tmp; }
  { void(* *tmp)(double *, double *, double *, double *, int, double const *, double const *, int) = &p->compute_geometry; (void)tmp; }
  { void(* *tmp)(double *, double *, double const *) = &p->compute_midpoint_geometry; (void)tmp; }
}
struct _cffi_align__ufc_coordinate_mapping { char x; ufc_coordinate_mapping y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main", (void *)_cffi_f_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 0), (void *)_cffi_d_create_ffc_coordinate_mapping_da9227d5db9ccee7df09f8e66921caa8e4c2c832_coordinate_mapping_main },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufc_coordinate_mapping, signature),
                 sizeof(((ufc_coordinate_mapping *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "create", offsetof(ufc_coordinate_mapping, create),
              sizeof(((ufc_coordinate_mapping *)0)->create),
              _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "geometric_dimension", offsetof(ufc_coordinate_mapping, geometric_dimension),
                           sizeof(((ufc_coordinate_mapping *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "topological_dimension", offsetof(ufc_coordinate_mapping, topological_dimension),
                             sizeof(((ufc_coordinate_mapping *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "cell_shape", offsetof(ufc_coordinate_mapping, cell_shape),
                  sizeof(((ufc_coordinate_mapping *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "create_coordinate_finite_element", offsetof(ufc_coordinate_mapping, create_coordinate_finite_element),
                                        sizeof(((ufc_coordinate_mapping *)0)->create_coordinate_finite_element),
                                        _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "create_coordinate_dofmap", offsetof(ufc_coordinate_mapping, create_coordinate_dofmap),
                                sizeof(((ufc_coordinate_mapping *)0)->create_coordinate_dofmap),
                                _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "compute_physical_coordinates", offsetof(ufc_coordinate_mapping, compute_physical_coordinates),
                                    sizeof(((ufc_coordinate_mapping *)0)->compute_physical_coordinates),
                                    _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "compute_reference_coordinates", offsetof(ufc_coordinate_mapping, compute_reference_coordinates),
                                     sizeof(((ufc_coordinate_mapping *)0)->compute_reference_coordinates),
                                     _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "compute_reference_geometry", offsetof(ufc_coordinate_mapping, compute_reference_geometry),
                                  sizeof(((ufc_coordinate_mapping *)0)->compute_reference_geometry),
                                  _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "compute_jacobians", offsetof(ufc_coordinate_mapping, compute_jacobians),
                         sizeof(((ufc_coordinate_mapping *)0)->compute_jacobians),
                         _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "compute_jacobian_determinants", offsetof(ufc_coordinate_mapping, compute_jacobian_determinants),
                                     sizeof(((ufc_coordinate_mapping *)0)->compute_jacobian_determinants),
                                     _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "compute_jacobian_inverses", offsetof(ufc_coordinate_mapping, compute_jacobian_inverses),
                                 sizeof(((ufc_coordinate_mapping *)0)->compute_jacobian_inverses),
                                 _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "compute_geometry", offsetof(ufc_coordinate_mapping, compute_geometry),
                        sizeof(((ufc_coordinate_mapping *)0)->compute_geometry),
                        _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "compute_midpoint_geometry", offsetof(ufc_coordinate_mapping, compute_midpoint_geometry),
                                 sizeof(((ufc_coordinate_mapping *)0)->compute_midpoint_geometry),
                                 _CFFI_OP(_CFFI_OP_NOOP, 54) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufc_coordinate_mapping", 45, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_coordinate_mapping), offsetof(struct _cffi_align__ufc_coordinate_mapping, y), 0, 15 },
  { "ufc_dofmap", 48, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufc_finite_element", 51, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufc_shape", 52, _cffi_prim_int(sizeof(ufc_shape), ((ufc_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufc_coordinate_mapping", 45 },
  { "ufc_dofmap", 48 },
  { "ufc_finite_element", 51 },
  { "ufc_scalar_t", 42 },
  { "ufc_shape", 52 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  7,  /* num_globals */
  3,  /* num_struct_unions */
  1,  /* num_enums */
  5,  /* num_typenames */
  NULL,  /* no includes */
  59,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffc_cmaps_69586377a2dc871c8a222292b64406616e15d217(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffc_cmaps_69586377a2dc871c8a222292b64406616e15d217(void) { return NULL; }
#  else
     initlibffc_cmaps_69586377a2dc871c8a222292b64406616e15d217(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffc_cmaps_69586377a2dc871c8a222292b64406616e15d217(void)
{
  return _cffi_init("libffc_cmaps_69586377a2dc871c8a222292b64406616e15d217", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffc_cmaps_69586377a2dc871c8a222292b64406616e15d217(void)
{
  _cffi_init("libffc_cmaps_69586377a2dc871c8a222292b64406616e15d217", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
