demos-python: &demos-python
  name: Run demos (Python, serial)
  command: |
    cd Scripts
    python3 ./understanding_mesh_workflow.py

folder-tree: &folder-tree
  name: Get folder tree
  command: |
    ls


version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: quay.io/fenicsproject/dolfinx:dev-env-real # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: *demos-python